version: '3.8'

services:
  app:
    build: 
      context: ./app
    container_name: MissionControl
    volumes: 
      - ./app/:/usr/src/app/
    ports:
      - 8099:8000
    depends_on:
      - db
  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_PASSWORD: "bad_password"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: